import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = file => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8'));
const write = (file, value) => fs.writeFileSync(path.join(root, file), JSON.stringify(value, null, 2) + '\n');
const metadata = read('package.json');
const plugin = read('plugin.json');
plugin.version = metadata.version;
write('plugin.json', plugin);
// The portable manifest owns plugin metadata; generate the compatibility overlay.
fs.mkdirSync(path.join(root, '.codex-plugin'), { recursive: true });
write('.codex-plugin/plugin.json', {
  name: plugin.name, version: plugin.version, description: plugin.description,
  skills: './skills/', interface: plugin.extensions['com.openai'].interface,
});
await build({
  absWorkingDir: root,
  entryPoints: ['src/cli.js'], outfile: 'dist/cli.js',
  bundle: true, platform: 'node', format: 'esm', target: 'node22.12',
  banner: { js: "// Generated by npm run build; edit src/ instead.\nimport { createRequire } from 'node:module'; const require = createRequire(import.meta.url);" },
  logLevel: 'info',
});
